include:
  - project: development/tools/gitlab-ci-templates
    ref: master
    file: /nodejs/all.yml

variables:
  GITHUB_URL: https://github.com/Paciolan/eslint-config.git

stages:
  - build
  - test
  - publish

Build:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/build.yml
  extends: .nodejs_build

Test:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/lint_test.yml
  extends: .nodejs_lint_test

Publish:
  # https://gitlabdev.paciolan.info/development/tools/gitlab-ci-templates/blob/master/nodejs/publish.yml
  extends: .nodejs_publish_semantic_release
  script:
    # npm publish is dumb and will include this file
    - rm changelog.config.js
    # set repository to github for npm link
    - node -e "require('fs').writeFileSync('./package.json', JSON.stringify(Object.assign(require('./package.json'), {repository:{type:'git',url:'$GITHUB_URL'}}), null, 2), 'utf8')"
    - semantic-release
  after_script:
    - echo https://www.npmjs.com/package/$(node -p "require('./package.json').name")
